

name: GitHub Pages

on:
  push:
    branches:
      - main


jobs:
  runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v3


        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '16'


        - run: npm ci
        - run: npm run build


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
